version: '3'

vars:
  APP_NAME: 'crc64'
  OUTPUT_DIR: bin
  MAIN_PACKAGE: .
  LDFLAGS: -s -w
  VERSION: '{{default "0.0.0" (env "S3CRC_VERSION")}}'

tasks:
  default:
    desc: Display available tasks.
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the project for the current platform.
    cmds:
      - task: prepare:output
      - task: build:{{OS}}

  build:linux:
    internal: true
    cmds:
      - go build -trimpath -ldflags "{{.LDFLAGS}}" -o {{.OUTPUT_DIR}}/{{.APP_NAME}} {{.MAIN_PACKAGE}}

  build:windows:
    internal: true
    cmds:
      - powershell -NoProfile -Command "if (Test-Path 'resource.syso') { Remove-Item -Force 'resource.syso' }"
      - go run github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest -icon=icon.ico -company="S3 CRC Contributors" -product-name="s3-crc" -product-version={{.VERSION}} -file-version={{.VERSION}} -original-name="s3-crc.exe" -description="S3 CRC checksum utility"{{if eq .ARCH "amd64"}} -64{{end}}
      - go build -trimpath -ldflags "{{.LDFLAGS}}" -o {{.OUTPUT_DIR}}/{{.APP_NAME}}.exe {{.MAIN_PACKAGE}}
      - powershell -NoProfile -Command "if (Test-Path 'resource.syso') { Remove-Item -Force 'resource.syso' }"

  prepare:output:
    internal: true
    cmds:
      - task: prepare:output:{{OS}}

  prepare:output:linux:
    internal: true
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}

  prepare:output:windows:
    internal: true
    cmds:
      - powershell -NoProfile -Command "New-Item -ItemType Directory -Force -Path '{{.OUTPUT_DIR}}' | Out-Null"

  clean:
    desc: Remove build artifacts.
    cmds:
      - task: clean:{{OS}}

  clean:linux:
    internal: true
    cmds:
      - rm -rf {{.OUTPUT_DIR}}
      - rm -f resource.syso

  clean:windows:
    internal: true
    cmds:
      - powershell -NoProfile -Command "if (Test-Path '{{.OUTPUT_DIR}}') { Remove-Item -Recurse -Force '{{.OUTPUT_DIR}}' }"
      - powershell -NoProfile -Command "if (Test-Path 'resource.syso') { Remove-Item -Force 'resource.syso' }"
