version: '3'

vars:
  APP_NAME: 'crc64' # Must match the binary name in Cargo.toml
  OUTPUT_DIR: bin
  VERSION: '{{default "0.0.0" (env "S3CRC_VERSION")}}'

tasks:
  default:
    desc: Display available tasks.
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the project for the current platform.
    cmds:
      - task: prepare:output
      - task: build:{{OS}}

  build:linux:
    internal: true
    cmds:
      - cargo build --release
      - cp target/release/{{.APP_NAME}} {{.OUTPUT_DIR}}/{{.APP_NAME}}
      - cp icon.ico {{.OUTPUT_DIR}}/icon.ico

  build:windows:
    internal: true
    cmds:
      - cargo build --release
      - powershell -NoProfile -Command "Copy-Item -Force 'target\\release\\{{.APP_NAME}}.exe' '{{.OUTPUT_DIR}}\\{{.APP_NAME}}.exe'"
      - powershell -NoProfile -Command "Copy-Item -Force 'icon.ico' '{{.OUTPUT_DIR}}\\icon.ico'"

  prepare:output:
    internal: true
    cmds:
      - task: prepare:output:{{OS}}

  prepare:output:linux:
    internal: true
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}

  prepare:output:windows:
    internal: true
    cmds:
      - powershell -NoProfile -Command "New-Item -ItemType Directory -Force -Path '{{.OUTPUT_DIR}}' | Out-Null"

  clean:
    desc: Remove build artifacts.
    cmds:
      - task: clean:{{OS}}

  clean:linux:
    internal: true
    cmds:
      - rm -rf {{.OUTPUT_DIR}}
      - rm -rf target

  clean:windows:
    internal: true
    cmds:
      - powershell -NoProfile -Command "if (Test-Path '{{.OUTPUT_DIR}}') { Remove-Item -Recurse -Force '{{.OUTPUT_DIR}}' }"
      - powershell -NoProfile -Command "if (Test-Path 'target') { Remove-Item -Recurse -Force 'target' }"

  fmt:
    desc: Format Rust sources.
    cmds:
      - cargo fmt --all

  fmt:check:
    internal: true
    cmds:
      - cargo fmt --all -- --check

  lint:
    desc: Run Clippy with warnings as errors.
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  test:
    desc: Execute the test suite.
    cmds:
      - cargo test

  check:
    desc: Run formatting, linting, and tests.
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
